### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by luisoala** [shift-happens-benchmark/icml-2022#116]
hi all is this project still maintained and accepting contributions?

**Comment by stes** [comment]
Hi @luisoala , yes it is, please feel free to contribute models/tasks/etc!

**Comment by luisoala** [comment]
thanks! ill have a look at the docs and give it a try

**Comment by luisoala** [comment]
are there still examples for task, dataset and model additions? https://github.com/shift-happens-benchmark/icml-2022/blob/main/examples gives a 404

**Comment by stes** [comment]
Hi @luisoala , I think what you are looking for is here:
- Models: https://github.com/shift-happens-benchmark/icml-2022/tree/main/shifthappens/models
- Task definitions: https://github.com/shift-happens-benchmark/icml-2022/tree/main/shifthappens/tasks

Especially for the tasks, if you go into the invidiual packages you will find further information in the README files, e.g. here: https://github.com/shift-happens-benchmark/icml-2022/tree/main/shifthappens/tasks/imagenet_3dcc
