### ISSUE TITLE
Add verbose option to Model.get_imagenet_predictions

### ISSUE THREAD

**Issue by zimmerrol** [shift-happens-benchmark/icml-2022#55]
We should think about adding an option for showing the progress when calculating the predictions for the ImageNet validation set [here](https://github.com/shift-happens-benchmark/icml-2022/blob/main/shifthappens/models/base.py#L165).

**Comment by stes** [comment]
I made a proposal for how to handle this (and other global config options to come) in PR #75 . Let me know what you think.
