### ISSUE TITLE
Improve documentation coverage

### ISSUE THREAD

**Issue by stes** [shift-happens-benchmark/icml-2022#82]
Coverage is quite bad currently and should be improved:

```
$ interrogate --ignore-nested-functions --ignore-private --ignore-semiprivate --ignore-init-method -v shifthappens
====== Coverage for /home/stes/projects/icml-2022/shifthappens/ =======
------------------------------- Summary -------------------------------
| Name                            |  Total |  Miss |  Cover |  Cover% |
|---------------------------------|--------|-------|--------|---------|
| __init__.py                     |      1 |     0 |      1 |    100% |
| benchmark.py                    |      6 |     0 |      6 |    100% |
| model_comparison.py             |      5 |     3 |      2 |     40% |
| utils.py                        |      4 |     1 |      3 |     75% |
| data/__init__.py                |      1 |     1 |      0 |      0% |
| data/base.py                    |     12 |     7 |      5 |     42% |
| data/imagenet.py                |      6 |     0 |      6 |    100% |
| data/torch.py                   |     10 |     6 |      4 |     40% |
| models/__init__.py              |      1 |     1 |      0 |      0% |
| models/base.py                  |      8 |     1 |      7 |     88% |
| models/mixins.py                |      6 |     0 |      6 |    100% |
| models/torchvision.py           |      4 |     0 |      4 |    100% |
| task_data/__init__.py           |      1 |     1 |      0 |      0% |
| task_data/task_metadata.py      |      2 |     1 |      1 |     50% |
| task_data/task_registration.py  |      3 |     2 |      1 |     33% |
| tasks/__init__.py               |      1 |     1 |      0 |      0% |
| tasks/base.py                   |      9 |     1 |      8 |     89% |
| tasks/metrics.py                |      2 |     0 |      2 |    100% |
| tasks/mixins.py                 |      6 |     0 |      6 |    100% |
| tasks/task_result.py            |      4 |     3 |      1 |     25% |
| tasks/utils.py                  |      3 |     0 |      3 |    100% |
|---------------------------------|--------|-------|--------|---------|
| TOTAL                           |     95 |    29 |     66 |   69.5% |
----------- RESULT: FAILED (minimum: 80.0%, actual: 69.5%) ------------
```

**Comment by zimmerrol** [comment]
Actually, the coverage is much better if you exclude magic functions  & I don't see a reason why we should enforce that docstrings are added for those functions as they should be self-explanatory:


    interrogate --ignore-nested-functions --ignore-private --ignore-semiprivate --ignore-init-method --ignore-magic -v shifthappens
    =================== Coverage for C:\Users\Roland\source\repos\shifthappens-icml-2022\shifthappens\ ====================
    ------------------------------------------------------- Summary -------------------------------------------------------
    | Name                                        |           Total |           Miss |           Cover |           Cover% |
    |---------------------------------------------|-----------------|----------------|-----------------|------------------|
    | __init__.py                                 |               1 |              0 |               1 |             100% |
    | benchmark.py                                |               6 |              0 |               6 |             100% |
    | model_comparison.py                         |               5 |              3 |               2 |              40% |
    | utils.py                                    |               4 |              1 |               3 |              75% |
    | data\__init__.py                            |               1 |              1 |               0 |               0% |
    | data\base.py                                |               7 |              2 |               5 |              71% |
    | data\imagenet.py                            |               6 |              0 |               6 |             100% |
    | data\torch.py                               |               4 |              0 |               4 |             100% |
    | models\__init__.py                          |               1 |              1 |               0 |               0% |
    | models\base.py                              |               7 |              0 |               7 |             100% |
    | models\mixins.py                            |               6 |              0 |               6 |             100% |
    | models\torchvision.py                       |               4 |              0 |               4 |             100% |
    | task_data\__init__.py                       |               1 |              1 |               0 |               0% |
    | task_data\task_metadata.py                  |               2 |              1 |               1 |              50% |
    | task_data\task_registration.py              |               2 |              1 |               1 |              50% |
    | tasks\__init__.py                           |               1 |              1 |               0 |               0% |
    | tasks\base.py                               |               8 |              0 |               8 |             100% |
    | tasks\metrics.py                            |               2 |              0 |               2 |             100% |
    | tasks\mixins.py                             |               6 |              0 |               6 |             100% |
    | tasks\task_result.py                        |               2 |              1 |               1 |              50% |
    | tasks\utils.py                              |               3 |              0 |               3 |             100% |
    |---------------------------------------------|-----------------|----------------|-----------------|------------------|
    | TOTAL                                       |              79 |             13 |              66 |            83.5% |
    ----------------------------------- RESULT: PASSED (minimum: 80.0%, actual: 83.5%) ------------------------------------
